---
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mgr_group_name: mgrs

ceph_origin: 'repository' # or 'distro' or 'local'
ceph_stable: true # use ceph stable branch
ceph_stable_release: luminous

# Journal size should be 2 * (expected throughput * filestore max sync interval)
# Our expected max throughput on non-SSD drives is about 140MB/s
# filestore max sync interval default is 5. So 14GB should be the journal size
# Let's round that up to 20GB as a lazy/safe option
journal_size: "{{ osd_journal_size | default('20480') }}"

# Set osd filesystem settings
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: filestore


radosgw_civetweb_num_threads: 4096
ceph_conf_overrides_all:
   global:
     osd_pool_default_pg_num: 128
     osd_pool_default_pgp_num: 128
     mon_osd_down_out_interval: 900
     osd_heartbeat_min_size: 9000
   client:
     rbd_cache_size: 134217728
     rbd_cache_max_dirty: 50331648
     rbd_cache_max_dirty_age: 15
     rbd_cache_target_dirty: 33554432

ceph_conf_overrides_extra: {}
# This allows us to have ceph_conf_overrides per group without overwriting the
# overall ceph_conf_overrides_all (above).
# Additionally, we can set extras as a variable override without having to
# respecify all the above settings.
ceph_conf_overrides: "{{ ceph_conf_overrides_all | combine(ceph_conf_overrides_extra, recursive = True) }}"

os_tuning_params:
  - { name: kernel.pid_max, value: 4194303 }
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.swappiness, value: 10 }
  - { name: net.ipv4.tcp_tw_recycle, value: 1 }
  - { name: net.ipv4.tcp_tw_reuse, value: 1 }
  - { name: net.ipv4.tcp_fin_timeout, value: 10 }
  - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
  - { name: net.ipv4.tcp_max_syn_backlog, value: 4096 }
  - { name: net.core.rmem_max, value: 33554432 }
  - { name: net.core.wmem_max, value: 33554432 }
  - { name: net.core.rmem_default, value: 33554432 }
  - { name: net.core.wmem_default, value: 33554432 }
  - { name: net.core.optmem_max, value: 40960 }
  - { name: net.ipv4.tcp_rmem, value: 4096 87380 33554432 }
  - { name: net.ipv4.tcp_wmem, value: 4096 65536 33554432 }
  - { name: net.netfilter.nf_conntrack_max, value: 1000000 }

disable_transparent_hugepage: false
containerized_deployment: false
cephx: true
