---
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws

ceph_origin: 'upstream' # or 'distro' or 'local'
ceph_stable: true # use ceph stable branch
ceph_stable_release: jewel

radosgw_civetweb_num_threads: 1024
ceph_conf_overrides:
   global:
     osd_pool_default_pg_num: 32
     osd_pool_default_pgp_num: 32
     mon_osd_down_out_interval: 900

disable_transparent_hugepage: false
